// dev-env.mjs — regenerate web/.env.local for local development.
//
// .env.local is gitignored (secrets) so it vanishes whenever a fresh
// worktree is checked out or a linked worktree is reaped. This script
// rebuilds it deterministically from the machine's own credentials:
//
//   FIREBASE_WEB_API_KEY  ← `secret get firebase.web_api_key` (macOS Keychain)
//                            else GCP Secret Manager `firebase-web-api-key`
//   GOOGLE_ACCESS_TOKEN   ← `gcloud auth application-default print-access-token`
//                            (Firestore reads; ~1h TTL — re-run to refresh)
//   GCP_PROJECT / VERTEX_* ← static
//
// Usage:  node web/scripts/dev-env.mjs   (run from repo root or web/)
//         then: npm --prefix web run dev
//
// Recovery is now ONE command — no manual env hunting after a worktree wipe.

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB_ROOT = resolve(HERE, "..");
const ENV_PATH = resolve(WEB_ROOT, ".env.local");

const PROJECT = "dancinlab";

function sh(cmd) {
  return execSync(cmd, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
}
function trySh(cmd) {
  try {
    return sh(cmd);
  } catch {
    return "";
  }
}

// 1. Firebase web API key (static, public-ish client key).
let fbKey = trySh("secret get firebase.web_api_key");
if (!fbKey) {
  fbKey = trySh(
    `gcloud --project ${PROJECT} secrets versions access latest --secret=firebase-web-api-key`
  );
}
if (!fbKey) {
  console.error(
    "[dev-env] FIREBASE_WEB_API_KEY not found.\n" +
      "  try: secret get firebase.web_api_key\n" +
      "   or: gcloud --project dancinlab secrets versions access latest --secret=firebase-web-api-key"
  );
  process.exit(1);
}

// 2. GCP access token for Firestore (expires ~1h — re-run to refresh).
const token = trySh("gcloud auth application-default print-access-token");
if (!token) {
  console.error(
    "[dev-env] GOOGLE_ACCESS_TOKEN unavailable.\n" +
      "  run: gcloud auth application-default login"
  );
  process.exit(1);
}

const body = [
  "# AUTO-GENERATED by web/scripts/dev-env.mjs — do not commit (gitignored).",
  "# Re-run `node web/scripts/dev-env.mjs` to refresh (token TTL ~1h).",
  "GCP_PROJECT=dancinlab",
  "GOOGLE_CLOUD_PROJECT=dancinlab",
  "VERTEX_LOCATION=us-central1",
  "VERTEX_MODEL=gemini-2.5-flash",
  `FIREBASE_WEB_API_KEY=${fbKey}`,
  `NEXT_PUBLIC_FIREBASE_WEB_API_KEY=${fbKey}`,
  `GOOGLE_ACCESS_TOKEN=${token}`,
  "",
].join("\n");

writeFileSync(ENV_PATH, body);
console.log(`✓ wrote ${ENV_PATH}`);
console.log(`  FIREBASE_WEB_API_KEY  ${fbKey.slice(0, 8)}…  ✓`);
console.log(`  GOOGLE_ACCESS_TOKEN   ${token.slice(0, 8)}…  ✓ (re-run to refresh)`);
console.log(`\nnext:  npm --prefix web run dev`);
