#!/usr/bin/env python3
"""
MATH-SPECTRA probe6 — does cut-and-project gap-labeling extend to 2D quasicrystals
with a HIGHER-RANK Z-module (not a single 1D irrational rotation)?
=====================================================================================

THREAD CONTEXT (the 1D arc, complete):
  probe4 (🟢): Fibonacci hopping chain gaps land on the irrational-rotation module
    Z + Z*alpha, alpha = 1/phi = the letter frequency (left-Perron entry). 8/8 gaps.
  probe5 (🟢): the module GENERATOR is substitution-specific = the Perron letter
    frequency: silver-mean -> Z+Z*(1/sqrt2), period-doubling -> dyadic Z[1/2],
    Thue-Morse -> NOT a single irrational-rotation module. "where-arithmetic-lives"
    map charted for 1D substitution chains.

  ALL of probe1-5 were 1D (substitution chains, single-irrational rotation modules).

NEW AXIS (probe6, genuine — beyond 1D):
  In 1D the gap-label module is generated by ONE irrational (a single rotation number
  = the letter frequency). In a TRUE 2D quasicrystal the gap-labeling theorem (Bellissard
  K-theory / cut-and-project) predicts the labels lie in a HIGHER-RANK Z-module set by
  the dimension of the cut-and-project lattice -- NOT a single 1D rotation number.

  Ammann-Beenker (octagonal, 8-fold, silver-mean family) is the cleanest 2D test:
  it is the canonical cut-and-project of Z^4 -> R^2 (4D hypercubic to 2D physical
  space, with a regular-octagon acceptance window in the 2D internal space). Its gap
  labels are known (Bellissard / Kraus-Zilberberg, octagonal-tiling literature) to lie
  in the silver-mean module:
        IDOS in gap  ==  (1/8) * ( a + b*sqrt(2) ),   a,b in Z
  i.e. the ring Z[sqrt2] scaled by 1/8 (the 8-fold symmetry / four projection
  directions). Equivalently  IDOS = p + q*sqrt2  with small p,q rationals of
  denominator dividing 8 -- a RANK-2 (over Z, in {1, sqrt2}) module, the 2D
  cut-and-project lattice's signature, NOT a single 1D rotation orbit {n*alpha mod 1}.

PRE-REGISTERED HYPOTHESIS (frozen-first, c16/c9 -- anti-tune-to-green):
  (A) The major spectral gaps of the Ammann-Beenker vertex tight-binding model carry
      IDOS plateaus that lie in the SILVER-MEAN 2D module
          M_AB = { a + b*sqrt2 : a,b in (1/8)Z }   (the Z[sqrt2]/8 ring; rank-2 over
          Z in the basis {1, sqrt2}, the cut-and-project module),
      and fit it strictly better than a generic small-rational ladder p/q.
  (B) This 2D module is DISTINCT from a single 1D irrational rotation: the gaps do NOT
      all collapse onto {n*alpha mod 1} for any single alpha (Fibonacci 1/phi or even
      the 1D silver 1/sqrt2). The rank-2 {1, sqrt2} structure is needed.
  (C) CONTROL: a periodic 2D square lattice (same vertex tight-binding, hopping=1) has
      essentially NO gaps in its (single connected) band -- no fractal gap ladder, no
      sqrt2 module needed; its (trivial) IDOS values are plain rationals.

  FALSIFIER (honest, c9): if the AB gaps do NOT fit M_AB, or fit a TRIVIAL single 1D
  rotation just as well (so rank-2 is unnecessary), or the periodic control ALSO shows
  the same module -> 🔴. If the patch/window is too small to resolve clean gaps (gap
  widths comparable to finite-size level spacing) -> honest 🟠 INCONCLUSIVE, NOT a
  forced match.

  CLAIM UNDER TEST: cut-and-project gap-labeling extends from 1D (single-irrational
  rotation module) to 2D quasicrystals (higher-RANK Z-module set by the cut-and-project
  lattice). 🟢 if confirmed for Ammann-Beenker, 🔴 if not, 🟠 if under-resolved.

RUN:
  /Users/mini/dancinlab/demiurge/scripts/scratch/mathvenv/bin/python \
      scripts/scratch/math_spectra/probe6_2d_quasicrystal_gaplabeling.py

METHOD (pure linear algebra, exact tight-binding, FREE / LOCAL -- no GPU):
  CONSTRUCTION (Ammann-Beenker via cut-and-project, the standard octagonal projection):
    - Star of 4 unit vectors e_k = (cos(k*pi/4), sin(k*pi/4)), k=0..3 spanning R^2
      physical, with the COMPLEMENTARY 4 directions f_k = (cos(3k*pi/4), sin(3k*pi/4))
      spanning R^2 internal (perp space). This is the canonical Z^4 -> R^2 + R^2
      octagonal cut-and-project (de Bruijn / Beenker).
    - For each integer point n in Z^4 (bounded box), physical image x = sum n_k e_k,
      internal image x* = sum n_k f_k. ACCEPT n iff x* lies inside the regular-octagon
      acceptance window (the projection of the 4D unit hypercube = a regular octagon).
    - Accepted physical points = Ammann-Beenker vertices. Edges = vertex pairs at the
      tiling edge length (unit), i.e. nearest neighbours -> the tiling graph.
    - Vertex tight-binding: H = adjacency (hopping 1 on each tiling edge). eigvalsh.
  READOUT (reuses probe4/5 machinery):
    - sorted spectrum -> IDOS empirical CDF; in each major gap IDOS = (#eigs<=E_lo)/N.
    - locate major gaps -> test plateau against:
        * M_AB silver 2D module  a + b*sqrt2, a,b in (1/8)Z  (the cut-and-project module)
        * single 1D rotation {n*alpha mod 1}, alpha=1/sqrt2 and alpha=1/phi  (1D control)
        * generic small rationals p/q                         (trivial floor)
    - periodic square-lattice control: same readout, expect no gap ladder.

CAVEAT (c9): finite patch under OPEN boundary (a finite cluster). IDOS k/N converges to
  the infinite-volume gap label as N->inf; residuals are O(1/N) + boundary-mode limited.
  We test clustering/fit + module DISTINCTION, not exact equality. Boundary (dangling)
  vertices are trimmed (coordination filter) to reduce edge artefacts; the bulk gap
  structure is the discriminating signal.
"""

import json
import math
import os

import numpy as np

SQRT2 = math.sqrt(2.0)
GAMMA_SILVER_1D = 1.0 / SQRT2                # 1D silver letter freq (probe5)
GAMMA_FIB_1D = (math.sqrt(5.0) - 1.0) / 2.0  # 1D Fibonacci 1/phi (probe4)

OUTDIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "exports", "math-spectra"
)


# --------------------------------------------------------------------------- #
# Ammann-Beenker via cut-and-project Z^4 -> R^2(phys) + R^2(internal)
# --------------------------------------------------------------------------- #
def ab_cut_and_project(box=8):
    """Standard octagonal cut-and-project of Z^4 -> R^2(phys) + R^2(internal).
    Physical star  e_k = (cos k*pi/4, sin k*pi/4), k=0..3.
    Internal star  f_k = (cos 3k*pi/4, sin 3k*pi/4), k=0..3 (Galois conjugate, mult=3).
    ACCEPTANCE WINDOW = the projection of the unit 4-cube [-1/2,1/2]^4 into internal
    space (= a regular octagon). Membership: |x* . u_j| <= hw for the 4 octagon normals
    u_j = e_j, with hw = max over the 16 cube vertices of |u_j . (cubevert @ F)| =
    (1 + 1/sqrt2)/sqrt2 ... computed exactly from the cube projection (= 1.2071..).
    Accepted physical images = Ammann-Beenker vertices (tiling edge length exactly 1).
    Returns array of accepted physical-space vertex coordinates.
    """
    from itertools import product
    k = np.arange(4)
    E = np.stack([np.cos(k * np.pi / 4.0), np.sin(k * np.pi / 4.0)], axis=1)   # 4x2 phys
    F = np.stack([np.cos(3 * k * np.pi / 4.0), np.sin(3 * k * np.pi / 4.0)], axis=1)  # 4x2 int
    u = E  # octagon normals (8-fold; 4 axes +/- give 8 facets)

    # window half-width along each normal = the exact unit-cube projection extent
    cubeverts = np.array(list(product([-0.5, 0.5], repeat=4)))
    Wint = cubeverts @ F                       # 16 internal-space window vertices
    hw = float(np.max(np.abs(Wint @ u.T)))     # symmetric octagon -> single half-width

    pts = set()
    rng = range(-box, box + 1)
    for a in rng:
        for b in rng:
            for c in rng:
                for d in rng:
                    n = np.array([a, b, c, d], dtype=float)
                    xs = n @ F                 # internal image (2,)
                    if np.all(np.abs(u @ xs) <= hw + 1e-9):
                        xp = n @ E             # physical image
                        pts.add((round(xp[0], 6), round(xp[1], 6)))
    if not pts:
        return np.zeros((0, 2)), hw
    return np.array(sorted(pts)), hw


def nn_edges(P, edge_len=1.0, tol=1e-3):
    """Edges = vertex pairs at the Ammann-Beenker tiling edge length (= 1, the unit
    star-vector length), NOT the minimum pairwise distance (a boundary diagonal can be
    shorter). Returns adjacency matrix (float, hopping=1) and the edge length used."""
    N = len(P)
    diff = P[:, None, :] - P[None, :, :]
    D = np.sqrt((diff ** 2).sum(-1))
    np.fill_diagonal(D, np.inf)
    A = np.zeros((N, N), dtype=float)
    mask = np.abs(D - edge_len) < tol
    A[mask] = 1.0
    return A, float(edge_len)


def select_bulk(P, A, radius):
    """Take the central DISK of the cut-and-project patch (a connected bulk region) and
    re-derive its induced adjacency. A radial cut (not a coordination cascade) gives a
    clean, large bulk: the AB patch is a big disk and the only finite-size artefacts are
    the dangling edges of the outer ring, which a radius cut < patch radius removes in
    one shot without cascading the whole disk away. AB bulk coordination is 3..8."""
    r = np.sqrt((P ** 2).sum(1))
    keep = r <= radius
    idx = np.where(keep)[0]
    Pb = P[idx]
    Ab = A[np.ix_(idx, idx)]
    # one pass: drop any remaining strict danglers (coord<=1) created by the cut
    for _ in range(3):
        coord = Ab.sum(1)
        k2 = coord >= 2
        if k2.all():
            break
        j = np.where(k2)[0]
        Pb = Pb[j]
        Ab = Ab[np.ix_(j, j)]
    return Pb, Ab


def square_lattice(L):
    """Periodic 2D square lattice (LxL, PBC) vertex tight-binding control."""
    N = L * L
    A = np.zeros((N, N), dtype=float)

    def idx(i, j):
        return (i % L) * L + (j % L)

    for i in range(L):
        for j in range(L):
            a = idx(i, j)
            for di, dj in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                A[a, idx(i + di, j + dj)] = 1.0
    return A


# --------------------------------------------------------------------------- #
# IDOS gap reader (reuses probe4/5)
# --------------------------------------------------------------------------- #
def spectrum(A):
    return np.sort(np.linalg.eigvalsh(A))


def find_major_gaps(evals, n_gaps=10):
    N = len(evals)
    gaps = np.diff(evals)
    order = np.argsort(gaps)[::-1]
    out = []
    for i in order[:n_gaps]:
        out.append({
            "gap_width": float(gaps[i]),
            "idos_plateau": float((i + 1) / N),
            "E_lo": float(evals[i]),
            "E_hi": float(evals[i + 1]),
        })
    return out


# --------------------------------------------------------------------------- #
# Candidate module matchers
# --------------------------------------------------------------------------- #
def _circ(a, b):
    r = abs(a - b)
    return min(r, 1.0 - r)


def best_silver_2d_label(idos, denom=8, a_max=12, b_max=12):
    """Fit IDOS = (a + b*sqrt2)/denom  with a,b small integers (the AB cut-and-project
    module Z[sqrt2]/8). Returns (a, b, pred, res). Tests the RANK-2 {1,sqrt2} module."""
    best = None
    for a in range(-a_max, a_max + 1):
        for b in range(-b_max, b_max + 1):
            pred = (a + b * SQRT2) / denom
            # IDOS in [0,1]; only physically meaningful preds count, but allow wrap test
            if pred < -1e-9 or pred > 1.0 + 1e-9:
                continue
            r = abs(idos - pred)
            if best is None or r < best[3]:
                best = (a, b, float(pred), float(r))
    if best is None:
        return (0, 0, 0.0, abs(idos))
    return best


def best_irrational_label(idos, gen, n_max=20):
    best = None
    for n in range(-n_max, n_max + 1):
        pred = (n * gen) % 1.0
        r = _circ(idos, pred)
        if best is None or r < best[2]:
            best = (n, pred, r)
    return (best[0], float(best[1]), float(best[2]))


def best_rational_label(idos, q_max=20):
    best = None
    for q in range(1, q_max + 1):
        for p in range(0, q + 1):
            pred = p / q
            r = _circ(idos, pred)
            if best is None or r < best[3]:
                best = (p, q, float(pred), float(r))
    return best


def annotate(gaps):
    for g in gaps:
        idos = g["idos_plateau"]
        a, b, pred, r = best_silver_2d_label(idos)
        g["silver_2d_module"] = {"a": int(a), "b": int(b), "denom": 8,
                                 "pred": float(pred), "res": float(r),
                                 "uses_sqrt2": bool(b != 0)}
        n1, p1, r1 = best_irrational_label(idos, GAMMA_SILVER_1D)
        g["silver_1d_rotation"] = {"n": int(n1), "pred": float(p1), "res": float(r1)}
        nf, pf, rf = best_irrational_label(idos, GAMMA_FIB_1D)
        g["fib_1d_rotation"] = {"n": int(nf), "pred": float(pf), "res": float(rf)}
        rt = best_rational_label(idos)
        g["rational_floor"] = {"p": int(rt[0]), "q": int(rt[1]),
                               "pred": float(rt[2]), "res": float(rt[3])}
    return gaps


def module_fit_summary(gaps, span, sig_frac, res_tol):
    sig = [g for g in gaps if g["gap_width"] > sig_frac * span]
    if not sig:
        return {"n_sig": 0, "note": "no significant gaps", "sig_frac": sig_frac}

    def stats(key):
        res = [g[key]["res"] for g in sig]
        return {
            "n_matched": int(sum(1 for r in res if r < res_tol)),
            "median_res": float(np.median(res)),
            "max_res": float(np.max(res)),
        }

    s2 = stats("silver_2d_module")
    s1 = stats("silver_1d_rotation")
    f1 = stats("fib_1d_rotation")
    rt = stats("rational_floor")
    # how many sig gaps NEED sqrt2 (b!=0) for their best 2D-module fit
    needs_sqrt2 = int(sum(1 for g in sig
                          if g["silver_2d_module"]["uses_sqrt2"]
                          and g["silver_2d_module"]["res"] < res_tol))
    return {
        "n_sig": len(sig),
        "res_tol": res_tol,
        "sig_frac": sig_frac,
        "silver_2d_module": s2,
        "silver_1d_rotation": s1,
        "fib_1d_rotation": f1,
        "rational_floor": rt,
        "n_sig_needing_sqrt2": needs_sqrt2,
    }


# --------------------------------------------------------------------------- #
def main():
    out = {
        "probe": "MATH-SPECTRA-probe6",
        "title": ("2D quasicrystal gap-labeling: does cut-and-project arithmetic extend "
                  "from 1D single-irrational rotation to a higher-RANK 2D Z-module? "
                  "(Ammann-Beenker octagonal tiling, silver-mean family)"),
        "preregistered_hypothesis": (
            "frozen-first (c16/c9, anti-tune-to-green). (A) Ammann-Beenker vertex "
            "tight-binding major-gap IDOS plateaus lie in the silver-mean 2D "
            "cut-and-project module M_AB = {(a+b*sqrt2)/8 : a,b in Z} (the Z[sqrt2]/8 "
            "ring; RANK-2 over Z in basis {1,sqrt2}), fitting it better than a generic "
            "rational ladder. (B) M_AB is DISTINCT from any single 1D irrational rotation "
            "{n*alpha mod 1} (Fibonacci 1/phi or 1D-silver 1/sqrt2): the rank-2 {1,sqrt2} "
            "structure (b!=0 terms) is genuinely needed. (C) CONTROL: a periodic 2D square "
            "lattice shows NO such fractal gap ladder. FALSIFIER: gaps don't fit M_AB, or "
            "a single 1D rotation suffices (rank-2 unneeded), or the control also shows it "
            "-> RED. Under-resolved patch (gaps ~ level spacing) -> honest INCONCLUSIVE."),
        "construction": (
            "Ammann-Beenker via canonical octagonal cut-and-project Z^4 -> R^2(phys)+"
            "R^2(internal). Physical star e_k=(cos k*pi/4, sin k*pi/4), internal star "
            "f_k=(cos 3k*pi/4, sin 3k*pi/4), k=0..3. Accept n in Z^4 iff internal image "
            "lies in the regular-octagon window (proj of unit 4-cube). Accepted physical "
            "points = AB vertices; edges = nearest-neighbour (tiling edge length); vertex "
            "tight-binding H=adjacency (hopping 1). Under-coordinated boundary vertices "
            "trimmed. numpy eigvalsh -> IDOS plateau in each gap."),
        "module_generators": {
            "silver_2d_M_AB": "a + b*sqrt2 over 8 (Z[sqrt2]/8, rank-2 cut-and-project)",
            "silver_1d_rotation_1_over_sqrt2": GAMMA_SILVER_1D,
            "fib_1d_rotation_1_over_phi": GAMMA_FIB_1D,
        },
    }

    # ---------------- build Ammann-Beenker patch ---------------- #
    # cut-and-project Z^4 -> R^2; box sets the 4D scan extent (box=8 -> 17^4 candidates).
    P_raw, hw = ab_cut_and_project(box=10)
    A_raw, edge_len = nn_edges(P_raw, edge_len=1.0)
    # central-disk bulk (radius < patch radius removes the dangling outer ring in one cut)
    r_all = np.sqrt((P_raw ** 2).sum(1))
    bulk_radius = 0.72 * float(r_all.max())
    P, A = select_bulk(P_raw, A_raw, bulk_radius)
    ev = spectrum(A)
    span = float(ev[-1] - ev[0])
    coord = A.sum(1)

    sig_frac = 0.015
    res_tol = 0.01   # 2D finite cluster: looser than 1D ring (boundary modes); prereg
    gaps = annotate(find_major_gaps(ev, n_gaps=12))
    fit = module_fit_summary(gaps, span, sig_frac, res_tol)

    out["ammann_beenker"] = {
        "N_vertices_raw": int(len(P_raw)),
        "N_vertices_trimmed": int(len(P)),
        "window_half_width": float(hw),
        "edge_length": edge_len,
        "coordination_min": float(coord.min()) if len(coord) else 0.0,
        "coordination_max": float(coord.max()) if len(coord) else 0.0,
        "coordination_mean": float(coord.mean()) if len(coord) else 0.0,
        "spectrum_span": span,
        "E_min": float(ev[0]),
        "E_max": float(ev[-1]),
        "mean_level_spacing": float(span / max(1, len(ev) - 1)),
        "major_gaps": gaps,
        "module_fit": fit,
    }

    # ---------------- periodic square-lattice control ---------------- #
    Lsq = 28  # 784 sites, comparable scale
    Asq = square_lattice(Lsq)
    evsq = np.sort(np.linalg.eigvalsh(Asq))
    spansq = float(evsq[-1] - evsq[0])
    gaps_sq = annotate(find_major_gaps(evsq, n_gaps=12))
    fit_sq = module_fit_summary(gaps_sq, spansq, sig_frac, res_tol)
    out["periodic_square_control"] = {
        "N_sites": int(Lsq * Lsq),
        "spectrum_span": spansq,
        "largest_gap_width": float(max(np.diff(evsq))),
        "largest_gap_frac_of_span": float(max(np.diff(evsq)) / spansq),
        "n_significant_gaps": fit_sq.get("n_sig", 0),
        "module_fit": fit_sq,
        "note": ("known-periodic 2D band: connected spectrum, no fractal gap ladder; "
                 "any 'gap' is a finite-size level-spacing artefact, not a labelled gap"),
    }

    # ---------------- verdict logic (c9, anti-tune-to-green) ---------------- #
    n_sig = fit.get("n_sig", 0)
    mls = out["ammann_beenker"]["mean_level_spacing"]

    # resolution gate: are major gaps clearly above finite-size level spacing?
    if n_sig >= 2:
        sig_gaps = [g for g in gaps if g["gap_width"] > sig_frac * span]
        min_sig_gap = min(g["gap_width"] for g in sig_gaps)
        resolved = min_sig_gap > 5.0 * mls
    else:
        min_sig_gap = 0.0
        resolved = False

    s2 = fit.get("silver_2d_module", {})
    s1 = fit.get("silver_1d_rotation", {})
    f1 = fit.get("fib_1d_rotation", {})
    rtf = fit.get("rational_floor", {})

    # (A) 2D module fits all/most sig gaps
    A_module_fits = (n_sig >= 2 and s2.get("n_matched", 0) >= max(2, n_sig - 1))
    # (B) rank-2 needed: at least one sig gap genuinely needs sqrt2 (b!=0) within tol,
    #     AND a single 1D rotation does NOT fit all sig gaps as well.
    needs_sqrt2 = fit.get("n_sig_needing_sqrt2", 0) >= 1
    single_1d_suffices = (max(s1.get("n_matched", 0), f1.get("n_matched", 0)) >= n_sig
                          and max(s1.get("max_res", 9), f1.get("max_res", 9))
                          <= s2.get("max_res", 0) + res_tol)
    B_rank2_needed = needs_sqrt2 and not single_1d_suffices
    # (C) control has no comparable gap ladder
    C_control_clean = (out["periodic_square_control"]["largest_gap_frac_of_span"] < sig_frac
                       or fit_sq.get("n_sig", 0) == 0)

    if not resolved:
        verdict = "🟠 INCONCLUSIVE"
        passes = {"resolved": False, "A_module_fits": A_module_fits,
                  "B_rank2_needed": B_rank2_needed, "C_control_clean": C_control_clean}
    elif A_module_fits and B_rank2_needed and C_control_clean:
        verdict = "🟢 CONFIRMED"
        passes = {"resolved": True, "A_module_fits": True,
                  "B_rank2_needed": True, "C_control_clean": True}
    else:
        verdict = "🔴 NOT-CONFIRMED"
        passes = {"resolved": True, "A_module_fits": A_module_fits,
                  "B_rank2_needed": B_rank2_needed, "C_control_clean": C_control_clean}

    out["verdict_analysis"] = {
        "res_tol": res_tol,
        "sig_frac": sig_frac,
        "n_significant_gaps": n_sig,
        "mean_level_spacing": mls,
        "min_significant_gap_width": min_sig_gap,
        "resolved_gate_min_gap_gt_5x_spacing": bool(resolved),
        "A_silver_2d_module": {
            "n_matched": s2.get("n_matched", 0), "of": n_sig,
            "max_res": s2.get("max_res", None), "PASS": bool(A_module_fits)},
        "B_rank2_needed": {
            "n_sig_needing_sqrt2": fit.get("n_sig_needing_sqrt2", 0),
            "single_1d_silver_matched": s1.get("n_matched", 0),
            "single_1d_fib_matched": f1.get("n_matched", 0),
            "single_1d_suffices": bool(single_1d_suffices),
            "PASS": bool(B_rank2_needed)},
        "C_periodic_control_clean": {
            "largest_gap_frac": out["periodic_square_control"]["largest_gap_frac_of_span"],
            "PASS": bool(C_control_clean)},
        "rational_floor_max_res": rtf.get("max_res", None),
        "passes": passes,
    }
    out["verdict_tier"] = verdict

    if verdict.startswith("🟢"):
        out["finding"] = (
            "2D CUT-AND-PROJECT GAP-LABELING CONFIRMED. The Ammann-Beenker octagonal "
            "quasicrystal (cut-and-project of Z^4->R^2, %d trimmed vertices, mean "
            "coordination %.2f) shows %d significant spectral gaps whose IDOS plateaus "
            "land in the SILVER-MEAN 2D module M_AB = (a+b*sqrt2)/8 (Z[sqrt2]/8): %d/%d "
            "match (max res %.1e), with %d gap(s) GENUINELY requiring the sqrt2 (b!=0) "
            "term -- a single 1D irrational rotation {n*alpha mod 1} (1/sqrt2 or 1/phi) "
            "does NOT suffice (matched %d, %d of %d). The arithmetic that lived in a "
            "single 1D rotation number (probe4/5) becomes a higher-RANK Z-module in 2D, "
            "exactly the cut-and-project lattice signature. The periodic square-lattice "
            "control has no comparable gap ladder (largest gap %.1e of span). Cut-and-"
            "project gap-labeling EXTENDS to 2D quasicrystals with a rank-2 module."
        ) % (
            out["ammann_beenker"]["N_vertices_trimmed"],
            out["ammann_beenker"]["coordination_mean"], n_sig,
            s2.get("n_matched", 0), n_sig, s2.get("max_res", 0),
            fit.get("n_sig_needing_sqrt2", 0),
            max(s1.get("n_matched", 0), f1.get("n_matched", 0)),
            max(s1.get("n_matched", 0), f1.get("n_matched", 0)), n_sig,
            out["periodic_square_control"]["largest_gap_frac_of_span"],
        )
    elif verdict.startswith("🟠"):
        out["finding"] = (
            "INCONCLUSIVE (honest, c9): the finite Ammann-Beenker patch (%d trimmed "
            "vertices) did not resolve clean major gaps clearly above the finite-size "
            "mean level spacing (%.3e); n_sig=%d, min sig gap=%.3e. The construction is "
            "sound (cut-and-project, mean coordination %.2f) but a larger patch / cleaner "
            "window is needed for a definitive 2D module fit. Not forcing a match. "
            "Best 2D-module fit so far: %d/%d at max res %s. Breakthrough path: grow the "
            "4D box / sharpen the octagon window / use inflation instead of projection."
        ) % (
            out["ammann_beenker"]["N_vertices_trimmed"], mls, n_sig, min_sig_gap,
            out["ammann_beenker"]["coordination_mean"],
            s2.get("n_matched", 0), n_sig, str(s2.get("max_res", None)),
        )
    else:
        out["finding"] = (
            "NOT CONFIRMED (RED): Ammann-Beenker gaps did not validate the 2D rank-2 "
            "cut-and-project module as predicted. A_module_fits=%s, B_rank2_needed=%s "
            "(n_needing_sqrt2=%d, single_1d_suffices=%s), C_control_clean=%s. "
            "Either a single 1D rotation suffices (rank-2 unneeded) or the module does "
            "not fit. See verdict_analysis." % (
                A_module_fits, B_rank2_needed, fit.get("n_sig_needing_sqrt2", 0),
                single_1d_suffices, C_control_clean)
        )

    out["honest_caveat"] = (
        "Finite Ammann-Beenker cluster (%d vertices raw, %d after boundary trim) under "
        "OPEN boundary -- a finite patch, not infinite-volume. IDOS plateau k/N is a "
        "rational converging to the true gap label as N->inf (gap-labeling = Bellissard "
        "C*-algebra K-theory; for AB the labelled gaps lie in (1/8)Z[sqrt2]). Residuals "
        "are O(1/N) + boundary-mode limited; res_tol=%.3f pre-registered (looser than the "
        "1D ring probes because a 2D open cluster has more boundary states). We test "
        "module FIT + the DISTINCTION (rank-2 {1,sqrt2} vs single 1D rotation) + a "
        "periodic control, not exact equality. The window is the exact unit-4-cube "
        "projection (canonical AB octagon), not a tuned size. Boundary (under-coordinated) "
        "vertices are "
        "trimmed so the bulk gap structure -- the discriminating signal -- dominates over "
        "finite-edge artefacts. The full AB gap-label group is rank-2 over Z in {1,sqrt2} "
        "(the 8-fold cut-and-project module); we report the dominant low-index labels."
    ) % (len(P_raw), len(P), res_tol)

    os.makedirs(OUTDIR, exist_ok=True)
    path = os.path.join(OUTDIR, "probe6_2d_quasicrystal_gaplabeling.json")
    with open(path, "w") as f:
        json.dump(out, f, indent=2)

    # ------------------------- console summary ------------------------- #
    print("=" * 80)
    print("MATH-SPECTRA probe6 — 2D quasicrystal (Ammann-Beenker) gap-labeling")
    print("=" * 80)
    ab = out["ammann_beenker"]
    print(f"AB patch: {ab['N_vertices_raw']} raw -> {ab['N_vertices_trimmed']} trimmed "
          f"vertices; edge={ab['edge_length']:.4f}; coord {ab['coordination_min']:.0f}.."
          f"{ab['coordination_max']:.0f} (mean {ab['coordination_mean']:.2f})")
    print(f"spectrum span={ab['spectrum_span']:.4f}, mean level spacing="
          f"{ab['mean_level_spacing']:.4e}")
    print(f"\nsignificant gaps (>{sig_frac:.1%} of span), res_tol={res_tol}:")
    print(f"   {'IDOS':>9} {'gap_w':>8}  {'2D (a+b√2)/8':>18} {'res':>9}  "
          f"{'1D-silver res':>12} {'rat p/q':>8}")
    for g in gaps:
        if g["gap_width"] <= sig_frac * span:
            continue
        m = g["silver_2d_module"]
        print(f"   {g['idos_plateau']:>9.5f} {g['gap_width']:>8.4f}  "
              f"({m['a']:+d}{m['b']:+d}√2)/8={m['pred']:.5f} {m['res']:>9.2e}  "
              f"{g['silver_1d_rotation']['res']:>12.2e} "
              f"{g['rational_floor']['p']}/{g['rational_floor']['q']:>3}")
    va = out["verdict_analysis"]
    print(f"\nresolved (min gap > 5x spacing): {va['resolved_gate_min_gap_gt_5x_spacing']}")
    print(f"(A) 2D module fits      : PASS={va['A_silver_2d_module']['PASS']} "
          f"({va['A_silver_2d_module']['n_matched']}/{n_sig}, "
          f"max_res {va['A_silver_2d_module']['max_res']})")
    print(f"(B) rank-2 sqrt2 needed : PASS={va['B_rank2_needed']['PASS']} "
          f"(n_needing_sqrt2={va['B_rank2_needed']['n_sig_needing_sqrt2']}, "
          f"single_1d_suffices={va['B_rank2_needed']['single_1d_suffices']})")
    print(f"(C) periodic control    : PASS={va['C_periodic_control_clean']['PASS']} "
          f"(largest gap frac {va['C_periodic_control_clean']['largest_gap_frac']:.2e})")
    print(f"\nVERDICT: {out['verdict_tier']}")
    print(out["finding"])
    print(f"\nwrote {path}")


if __name__ == "__main__":
    main()
