#!/usr/bin/env python3
"""
AGA-RX RIBOZYME axis — rules-based siRNA design + in-silico off-target seed screen.

Targets (human mRNA, NCBI RefSeq):
  DKK1   NM_012242.4   dickkopf WNT signaling pathway inhibitor 1
  SRD5A2 NM_000348.4   steroid 5-alpha-reductase type 2 (finasteride target)
  AR     NM_000044.6   androgen receptor
  SFRP1  NM_003012.5   secreted frizzled related protein 1 (optional)

Design rules implemented (sense/guide convention: we score the 19mer
TARGET-MATCHING sense region; the guide/antisense is its reverse complement):

  Reynolds 2004    — GC 30-52%, A/U-rich 3' end of sense (=5' antisense), no
                     long runs, position-specific base preferences.
  Ui-Tei 2004      — A/U at antisense 5' (sense 3'), G/C at antisense 3'
                     (sense 5'), >=4 A/U in antisense positions 1-7, no GC
                     stretch >= 9.
  Amarzguioui 2004 — duplex-end thermodynamic asymmetry, A/U at antisense pos1.
  Thermodynamic    — nearest-neighbour Delta-G asymmetry between the two duplex
  asymmetry          ends (the guide 5' end should be LESS stable so RISC loads
                     the guide, not the passenger).

Off-target: seed = antisense positions 2-8 (the miRNA-like seed that drives
the bulk of siRNA off-target silencing). We count exact seed-complement (7mer
target-site) occurrences of each candidate's seed across the OTHER target
mRNAs on hand + the self transcript. A transcriptome-wide count needs the full
RefSeq mRNA set + a 3'UTR DB (see PIPELINE note in siRNA_design.md) and is
marked PARTIAL — we do NOT fabricate transcriptome hit counts.

Pure stdlib so it runs free on the pool.
"""

import re
from itertools import product

# RNA NN Delta-G (37C, Xia et al. 1998-style), used for relative end-stability.
NN_DG = {
    "AA": -0.93, "AU": -1.10, "UA": -1.33, "UU": -0.93,
    "CU": -2.08, "UC": -2.11, "GA": -2.35, "AG": -2.08,
    "GU": -2.11, "UG": -2.11, "CA": -2.11, "AC": -2.24,
    "GG": -3.26, "CC": -3.26, "GC": -3.42, "CG": -2.36,
}
for a, b in product("ACGU", repeat=2):
    NN_DG.setdefault(a + b, -2.0)


def dna2rna(s):
    return s.upper().replace("T", "U")


def revcomp_rna(s):
    c = {"A": "U", "U": "A", "G": "C", "C": "G"}
    return "".join(c[x] for x in reversed(s))


def gc(s):
    return 100.0 * (s.count("G") + s.count("C")) / len(s)


def has_run(s, n=4):
    return re.search(r"(.)\1{%d,}" % (n - 1), s) is not None


def max_gc_stretch(s):
    best = cur = 0
    for ch in s:
        cur = cur + 1 if ch in "GC" else 0
        best = max(best, cur)
    return best


def end_dg(window):
    return sum(NN_DG[window[i:i + 2]] for i in range(len(window) - 1))


def reynolds_score(sense):
    """Reynolds 8-criterion additive score on the SENSE 19mer.
    Position 1 = 5' of sense.  Antisense 5' = sense 3' end."""
    s = sense
    sc = 0
    g = gc(s)
    if 30 <= g <= 52:                                  # I.  GC 30-52%
        sc += 1
    if sum(1 for ch in s[14:19] if ch in "AU") >= 3:   # II. A/U-rich antisense 5'
        sc += 1
    if not has_run(s, 4):                              # III. no run >=4
        sc += 1
    if s[18] == "A":                                   # IV. A at sense pos19
        sc += 1
    if s[2] == "A":                                    # V.  A at sense pos3
        sc += 1
    if s[9] == "U":                                    # VI. U at sense pos10
        sc += 1
    if s[18] not in "GC":                              # VII. not G/C at pos19
        sc += 1
    if s[12] != "G":                                   # VIII. not G at pos13
        sc += 1
    return sc  # 0-8


def uitei_pass(sense):
    """Ui-Tei 4 rules, evaluated on the GUIDE (antisense)."""
    g = revcomp_rna(sense)
    ok = True
    reasons = []
    if g[0] not in "AU":
        ok = False; reasons.append("g5'!AU")
    if g[-1] not in "GC":
        ok = False; reasons.append("g3'!GC")
    if sum(1 for ch in g[:7] if ch in "AU") < 4:
        ok = False; reasons.append("<4AU(1-7)")
    if max_gc_stretch(g) >= 9:
        ok = False; reasons.append("GC>=9")
    return ok, reasons


def asymmetry(sense):
    """Thermodynamic end-asymmetry. Guide 5' end == revcomp of sense 3' end.
    ddG = DG(guide-3' end window) - DG(guide-5' end window).
    More NEGATIVE ddG => guide-5' end relatively unstable => GOOD asymmetry."""
    guide = revcomp_rna(sense)
    dg_g5 = end_dg(guide[:5])
    dg_g3 = end_dg(guide[-5:])
    return dg_g3 - dg_g5


def synthesizability(sense):
    """Synthesis-difficulty proxy (0-1, 1=easy). Penalize G-runs / high GC."""
    score = 1.0
    if re.search(r"G{4,}", sense):
        score -= 0.4
    if gc(sense) > 60:
        score -= 0.3
    if max_gc_stretch(sense) >= 9:
        score -= 0.2
    return max(0.0, score)


def slide_candidates(mrna, w=19):
    return [(i + 1, mrna[i:i + w]) for i in range(len(mrna) - w + 1)]


def seed_of(sense):
    """miRNA-like seed = guide (antisense) positions 2-8 (7mer)."""
    return revcomp_rna(sense)[1:8]


def count_seed_offtarget(seed, pools):
    """Count seed TARGET-SITE (revcomp of guide 7mer seed) occurrences across
    the mRNA pool strings (overlapping)."""
    site = revcomp_rna(seed)
    return sum(len(re.findall("(?=%s)" % re.escape(site), seq)) for _, seq in pools)


# ---------------------------------------------------------------- sequences
RAW = {}

RAW["DKK1"] = """
GCAGAGCTCTGTGCTCCCTGCAGTCAGGACTCTGGGACCGCAGGGGGCTCCCGGACCCTGACTCTGCAGCCGAACCGGCACGGTTTCGTGGGGACCCAGGCTTGCAAAGTGACGGTCATTTTCTCTTTCTTTCTCCCTCTTGAGTCCTTCTGAGATGATGGCTCTGGGCGCAGCGGGAGCTACCCGGGTCTTTGTCGCGATGGTAGCGGCGGCTCTCGGCGGCCACCCTCTGCTGGGAGTGAGCGCCACCTTGAACTCGGTTCTCAATTCCAACGCTATCAAGAACCTGCCCCCACCGCTGGGCGGCGCTGCGGGGCACCCAGGCTCTGCAGTCAGCGCCGCGCCGGGAATCCTGTACCCGGGCGGGAATAAGTACCAGACCATTGACAACTACCAGCCGTACCCGTGCGCAGAGGACGAGGAGTGCGGCACTGATGAGTACTGCGCTAGTCCCACCCGCGGAGGGGACGCAGGCGTGCAAATCTGTCTCGCCTGCAGGAAGCGCCGAAAACGCTGCATGCGTCACGCTATGTGCTGCCCCGGGAATTACTGCAAAAATGGAATATGTGTGTCTTCTGATCAAAATCATTTCCGAGGAGAAATTGAGGAAACCATCACTGAAAGCTTTGGTAATGATCATAGCACCTTGGATGGGTATTCCAGAAGAACCACCTTGTCTTCAAAAATGTATCACACCAAAGGACAAGAAGGTTCTGTTTGTCTCCGGTCATCAGACTGTGCCTCAGGATTGTGTTGTGCTAGACACTTCTGGTCCAAGATCTGTAAACCTGTCCTGAAAGAAGGTCAAGTGTGTACCAAGCATAGGAGAAAAGGCTCTCATGGACTAGAAATATTCCAGCGTTGTTACTGTGGAGAAGGTCTGTCTTGCCGGATACAGAAAGATCACCATCAAGCCAGTAATTCTTCTAGGCTTCACACTTGTCAGAGACACTAAACCAGCTATCCAAATGCAGTGAACTCCTTTTATATAATAGATGCTATGAAAACCTTTTATGACCTTCATCAACTCAATCCTAAGGATATACAAGTTCTGTGGTTTCAGTTAAGCATTCCAATAACACCTTCCAAAAACCTGGAGTGTAAGAGCTTTGTTTCTTTATGGAACTCCCCTGTGATTGCAGTAAATTACTGTATTGTAAATTCTCAGTGTGGCACTTACCTGTAAATGCAATGAAACTTTTAATTATTTTTCTAAAGGTGCTGCACTGCCTATTTTTCCTCTTGTTATGTAAATTTTTGTACACATTGATTGTTATCTTGACTGACAAATATTCTATATTGAACTGAAGTAAATCATTTCAGCTTATAGTTCTTAAAAGCATAACCCTTTACCCCATTTAATTCTAGAGTCTAGAACGCAAGGATCTCTTGGAATGACAAATGATAGGTACCTAAAATGTAACATGAAAATACTAGCTTATTTTCTGAAATGTACTATCTTAATGCTTAAATTATATTTCCCTTTAGGCTGTGATAGTTTTTGAAATAAAATTTAACATTTAATATCATGAAATGTTATAAGTAGACATACATTTTGGGATTGTGATCTTAGAGGTTTGTGTGTGTGTACGTATGTGTGTGTTCTACAAGAACGGAAGTGTGATATGTTTAAAGATGATCAGAGAAAAGACAGTGTCTAAATATAAGACAATATTGATCAGCTCTAGAATAACTTTAAAGAAAGACGTGTTCTGCATTGATAAACTCAAATGATCATGGCAGAATGAGAGTGAATCTTACATTACTACTTTCAAAAATAGTTTCCAATAAATTAATAATACCTA
"""

RAW["SRD5A2"] = """
CTGGGAGGGCAGCGGCCACCGGCGAGGAACACGGCGCGATGCAGGTTCAGTGCCAGCAGAGCCCAGTGCTGGCAGGCAGCGCCACTTTGGTCGCCCTTGGGGCACTGGCCTTGTACGTCGCGAAGCCCTCCGGCTACGGGAAGCACACGGAGAGCCTGAAGCCGGCGGCTACCCGCCTGCCAGCCCGCGCCGCCTGGTTCCTGCAGGAGCTGCCTTCCTTCGCGGTGCCCGCGGGGATCCTCGCCCGGCAGCCCCTCTCCCTCTTCGGGCCACCTGGGACGGTACTTCTGGGCCTCTTCTGCCTACATTACTTCCACAGGACATTTGTGTACTCACTGCTCAATCGAGGGAGGCCTTATCCAGCTATACTCATTCTCAGAGGCACTGCCTTCTGCACTGGAAATGGAGTCCTTCAAGGCTACTATCTGATTTACTGTGCTGAATACCCTGATGGGTGGTACACAGACATACGGTTTAGCTTGGGTGTCTTCTTATTTATTTTGGGAATGGGAATAAACATTCATAGTGACTATATATTGCGCCAGCTCAGGAAGCCTGGAGAAATCAGCTACAGGATTCCACAAGGTGGCTTGTTTACGTATGTTTCTGGAGCCAATTTCCTCGGTGAGATCATTGAATGGATCGGCTATGCCCTGGCCACTTGGTCCCTCCCAGCACTTGCATTTGCATTTTTCTCACTTTGTTTCCTTGGGCTGCGAGCTTTTCACCACCATAGGTTCTACCTCAAGATGTTTGAGGACTACCCCAAATCTCGGAAAGCCCTTATTCCATTCATCTTTTAAAGGAACCAAATTAAAAAGGAGCAGAGCTCCCACAATGCTGATGAAAACTGTCAAGCTGCTGAAACTGTAATTTTCATGATATAATAGTCCCGTATATATGTAATAGTAGGTCTCCTGGCGTTCTGCCAGCTGGCCTGGGGATTCTGAGTGGTGTCTGCTTAGAGTTTACTCCTACCCTTCCAGGGACCCCTATCCTGATCCCCAACTGAAGCTTCAAAAAGCCACTTTTCCAAATGGCGACAGTTGCTTCTTAGCTATTGCTCTGAGAAAGTACAAACTTCTCCTATGTCTTTCACCGGGCAATCCAAGTACATGTGGCTTCATACCCACTCCCTGTCAATGCAGGACAACTCTGTAATCAAGAATTTTTTGACTTGAAGGCAGTACTTATAGACCTTATTAAAGGTATGCATTTTATACATGTAACAGAGTAGCAGAAATTTAAACTCTGAAGCCACAAAGACCCAGAGCAAACCCACTCCCAAATGAAAACCCCAGTCATGGCTTCCTTTTTCTTGGTTAATTAGGAAAGATGAGAAATTATTAGGTAGACCTTGAATACAGGAGCCCTCTCCTCATAGTGCTGAAAAGATACTGATGCATTGACCTCATTTCAAATTTGTGCAGTGTCTTAGTTGATGAGTGCCTCTGTTTTCCAGAAGATTTCACAATCCCCGGAAAACTGGTATGGCTATTCTTGAAGGCCAGGTTTTAATAACCACAAACAAAAAGGCATGAACCTGGGTGGCTTATGAGAGAGTAGAGAACAACATGACCCTGGATGGCTACTAAGAGGATAGAGAACAGTTTTACAATAGACATTGCAAACTCTCATGTTTTTGGAAACTAGTGGCAATATCCAAATAATGAGTAGTGTAAAACAAAGAGAATTAATGATGAGGTTACATGCTGCTTGCCTCCACCAGATGTCCACAACAATATGAAGTACAGCAGAAGCCCCAAGCAACTTTCCTTTCCTGGAGCTTCTTCCTTGTAGTTCTCAGGACCTGTTCAAGAAGGTGTCTCCTAGGGGCAGCCTGAATGCCTCCCTCAAAGGACCTGCAGGCAGAGACTGAAAATTGCAGACAGAGGGGCACGTCTGGGCAGAAAACCTGTTTTGTTTGGCTCAGACATATAGTTTTTTTTTTTTTTACAAAGTTTCAAAAACTTAAAAATCAGGAGATTCCTTCATAAAACTCTAGCATTCTAGTTTCATTTAAAAAGTTGGAGGATCTGAACATACAGAGCCCACATTTCCACACCAGAACTGGAACTACGTAGCTAGTAAGCATTTGAGTTTGCAAACTCTTGTGAAGGGGTCACCCCAGCATGAGTGCTGAGATATGGACTCTCTAAGGAAGGGGCCGAACGCTTGTAATTGGAATACATGGAAATATTTGTCTTCTCAGGCCTATGTTTGCGGAATGCATTGTCAATATTTAGCAAACTGTTTTGACAAATGAGCACCAGTGGTACTAAGCACAGAAACTCACTATATAAGTCACATAGGAAACTTGAAAGGTCTGAGGATGATGTAGATTACTGAAAAATGCAAATTGCAATCATATAAATAAGTGTTTTTGTTGTTCATTAAATACCTTTAAATCATGGATGTTAAGCAGTTTTGTTTGAATTAAAATATCCTGGGACTTCTGGAGATTTTCACAAGGTATTGGGGTGTGCTTCCCTGTCCCGCCTGTCCCTCATTCCCATTCACCCTGTCTGTAGTGTCGTTTCCTTTCTTCTCTTCTCTCTTCATGAAATTAGGGGCTGTGTGCTGGAAATAAAGAAGTATGACTTATACAGCCTCTCAGCCACAATTCAGAACTACAAGGAAGTACAATAAAGGTGCAGGAAAACGTCATGAGGTTAGATGCCACTCCTGGTGCTGAGGAATACACAGGGGGAATGAACACACTTGGTGAAGTAAATCTTCAGGTGTAGCTTGAGCTCTGTGACATAAAAGACTTCCAGTTCTCTCCATGACATTGAAAACTACCTTGCTTAAGTCCTTTATTTTACTACCATGTAAAACATCCAGGCCGGTCCTTGAGATGAAATAAATATACAATAAATGGCAGTACTCAGTCTCAGGACAAAACCGCCATTTGGCAATTTCACTTTTTGCCACAAGAGGGCGCTTTCTAAAATAGTATTTAGTCCAACCTTGACTTAATTAGGTCCAACCCCAGTCCTGTTGCCTGATCGTGGACCTTTCAAGTTAGCATGATCGTGGAACTTCTTAATCTGAATATAGGGTAGAGTAGCGTGAACTCTATGAAAGCTGAAACCTTCCCTTGATAATTCAGGTATTCTCAGTGTTCTAGGGCTGTTGTGTTCAATGACAGTTTGTCATTGTTTAGGGCTAGGATATGTATGTGGATTAAATACAGTAAAGGTCTGAACATGTGCTCATCTCTAAACATATTTCTTCCCACTTTTAAAAATAGGGTGCAACAAAATTATAGTTAATTGAGGTTTCCATGGACTGTTTTTTGGCTAAAATAATCTAACAGTGTCCTAGCTCACAAGATACTCTATCTTGGTCTTGCTGAAGCTTTCACGGAAGAGGCGTTTTCCTGCCAACCTTGAAGAAAATGTTGAGTTTTGTTTGTTTTTCAGAATTTAGACTTAAAGAGCTGAAGCAGACCTCAGACATCAGCTATTCCTACCACTTCACATTATAGGTAGTGACACTGAGACCCACAGAGTTAAAAGGCCTCCTCACAGCTGGTACAGAGCTGGTCAGAGCAGCCATCTCATTTTGTCCCTTTGAGGGTCAGATGTATGCTTCTTCTGCTTAAGGCACAGCCTTTAGGGCTGCCATCTGGATTTCTACAGAGCTCATGCAGGAGAAAAATAGCCAGAGCTTAAGTGCTGTTGCATAGTTCAGTTTATACACCTATTGTCCCATGCCTGTTTGTGTGTGAGGCTTCCCTCGCTCCGTGGGAGCACCAGGCTCATGCCCTTTCATAAACCTATTTGACAGAATAGAGAGTTTTCCCTCATTGGTGTAGTCAAGACAACATGTGTGTTCAGCATGGAAAAAAGGTTTCAGGTCATAAACCCCCTTATCCCTAATGCTTACTTTCATAAAGAACAACAGTGGCTCCACTGTATTCTAAAAGGAAAAAGGAGCTCTAATGAGAAATACGCAATTAAACAGCTATTTAGGCGGCTTAGACCCTTTCAGGAACAAATAAATAAATCCGTGGTTTTACAACCCTGAAGTTTGATAATAGCTCTCTTGGATTTTTGTGGTTACCTCATGGCAATCTCACTAAGAAGCAGGGGAGCAAGCTCTTGGCACATGAAGGAATAGGCTCATGAAGATTCATTTCTTTTCCCGCTTGGCCTTTTGGTTCTCTAATAAGCTGTGAGCTGAGGTCCATGCAGGGAAAACAAGGAGGGTAACGGCAAATGTAAAGTGAATTTTTCTGGAGAAGGATGCTGATTATTTTATAGCATCTACACTATCCTATGATGAAAGAGGCATAGAGCCGGGTGGCAATGTGAGTTCTTGGGTGATTTAATAAGCCATCGAGTGGATTTAATTTCTAAGTAAGACATTTGTTTATTCTTTGTACAAGTCCATGGAGTTGTGATCTTAAAGAGTTCTGTGTTATTTGCATTGTGCCTCATTTCTCCCCATCAACCTTAGCTTGAGATTTGGATGAATAAAATAAATAACTGGAGAAGGTTAAAGTATGCACCAA
"""

RAW["AR"] = """
AGCGCCCCCTCCGAGATCCCGGGGAGCCAGCTTGCTGGGAGAGCGGGACGGTCCGGAGCAAGCCCAGAGGCAGAGGAGGCGACAGAGGGAAAAAGGGCCGAGCTAGCCGCTCCAGTGCTGTACAGGAGCCGAAGGGACGCACCACGCCAGCCCCAGCCCGGCTCCAGCGACAGCCAACGCCTCTTGCAGCGCGGCGGCTTCGAAGCCGCCGCCCGGAGCTGCCCTTTCCTCTTCGGTGAAGTTTTTAAAAGCTGCTAAAGACTCGGAGGAAGCAAGGAAAGTGCCTGGTAGGACTGACGGCTGCCTTTGTCCTCCTCCTCTCCACCCCGCCTCCCCCCACCCTGCCTTCCCCCCCCTCCCCCGTCTTCTCTCCCGCAGCTGCCTCAGTCGGCTACTCTCAGCCAACCCCCCTCACCACCCTTCTCCCCACCCGCCCCCCCGCCCCCGTCGGCCCAGCGCTGCCAGCCCGAGTTTGCAGAGAGGTAACTCCCTTTGGCTGCGAGCGGGCGAGCTAGCTGCACATTGCAAAGAAGGCTCTTAGGAGCCAGGCGACTGGGGAGCGGCTTCAGCACTGCAGCCACGACCCGCCTGGTTAGGCTGCACGCGGAGAGAACCCTCTGTTTTCCCCCACTCTCTCTCCACCTCCTCCTGCCTTCCCCACCCCGAGTGCGGAGCCAGAGATCAAAAGATGAAAAGGCAGTCAGGTCTTCAGTAGCCAAAAAACAAAACAAACAAAAACAAAAAAGCCGAAATAAAAGAAAAAGATAATAACTCAGTTCTTATTTGCACCTACTTCAGTGGACACTGAATTTGGAAGGTGGAGGATTTTGTTTTTTTCTTTTAAGATCTGGGCATCTTTTGAATCTACCCTTCAAGTATTAAGAGACAGACTGTGAGCCTAGCAGGGCAGATCTTGTCCACCGTGTGTCTTCTTCTGCACGAGACTTTGAGGCTGTCAGAGCGCTTTTTGCGTGGTTGCTCCCGCAAGTTTCCTTCTCTGGAGCTTCCCGCAGGTGGGCAGCTAGCTGCAGCGACTACCGCATCATCACAGCCTGTTGAACTCTTCTGAGCAAGAGAAGGGGAGGCGGGGTAAGGGAAGTAGGTGGAAGATTCAGCCAAGCTCAAGGATGGAAGTGCAGTTAGGGCTGGGAAGGGTCTACCCTCGGCCGCCGTCCAAGACCTACCGAGGAGCTTTCCAGAATCTGTTCCAGAGCGTGCGCGAAGTGATCCAGAACCCGGGCCCCAGGCACCCAGAGGCCGCGAGCGCAGCACCTCCCGGCGCCAGTTTGCTGCTGCTGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAAGAGACTAGCCCCAGGCAGCAGCAGCAGCAGCAGGGTGAGGATGGTTCTCCCCAAGCCCATCGTAGAGGCCCCACAGGCTACCTGGTCCTGGATGAGGAACAGCAACCTTCACAGCCGCAGTCGGCCCTGGAGTGCCACCCCGAGAGAGGTTGCGTCCCAGAGCCTGGAGCCGCCGTGGCCGCCAGCAAGGGGCTGCCGCAGCAGCTGCCAGCACCTCCGGACGAGGATGACTCAGCTGCCCCATCCACGTTGTCCCTGCTGGGCCCCACTTTCCCCGGCTTAAGCAGCTGCTCCGCTGACCTTAAAGACATCCTGAGCGAGGCCAGCACCATGCAACTCCTTCAGCAACAGCAGCAGGAAGCAGTATCCGAAGGCAGCAGCAGCGGGAGAGCGAGGGAGGCCTCGGGGGCTCCCACTTCCTCCAAGGACAATTACTTAGGGGGCACTTCGACCATTTCTGACAACGCCAAGGAGTTGTGTAAGGCAGTGTCGGTGTCCATGGGCCTGGGTGTGGAGGCGTTGGAGCATCTGAGTCCAGGGGAACAGCTTCGGGGGGATTGCATGTACGCCCCACTTTTGGGAGTTCCACCCGCTGTGCGTCCCACTCCTTGTGCCCCATTGGCCGAATGCAAAGGTTCTCTGCTAGACGACAGCGCAGGCAAGAGCACTGAAGATACTGCTGAGTATTCCCCTTTCAAGGGAGGTTACACCAAAGGGCTAGAAGGCGAGAGCCTAGGCTGCTCTGGCAGCGCTGCAGCAGGGAGCTCCGGGACACTTGAACTGCCGTCTACCCTGTCTCTCTACAAGTCCGGAGCACTGGACGAGGCAGCTGCGTACCAGAGTCGCGACTACTACAACTTTCCACTGGCTCTGGCCGGACCGCCGCCCCCTCCGCCGCCTCCCCATCCCCACGCTCGCATCAAGCTGGAGAACCCGCTGGACTACGGCAGCGCCTGGGCGGCTGCGGCGGCGCAGTGCCGCTATGGGGACCTGGCGAGCCTGCATGGCGCGGGTGCAGCGGGACCCGGTTCTGGGTCACCCTCAGCCGCCGCTTCCTCATCCTGGCACACTCTCTTCACAGCCGAAGAAGGCCAGTTGTATGGACCGTGTGGTGGTGGTGGGGGTGGTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGAGGCGGGAGCTGTAGCCCCCTACGGCTACACTCGGCCCCCTCAGGGGCTGGCGGGCCAGGAAAGCGACTTCACCGCACCTGATGTGTGGTACCCTGGCGGCATGGTGAGCAGAGTGCCCTATCCCAGTCCCACTTGTGTCAAAAGCGAAATGGGCCCCTGGATGGATAGCTACTCCGGACCTTACGGGGACATGCGTTTGGAGACTGCCAGGGACCATGTTTTGCCCATTGACTATTACTTTCCACCCCAGAAGACCTGCCTGATCTGTGGAGATGAAGCTTCTGGGTGTCACTATGGAGCTCTCACATGTGGAAGCTGCAAGGTCTTCTTCAAAAGAGCCGCTGAAGGGAAACAGAAGTACCTGTGCGCCAGCAGAAATGATTGCACTATTGATAAATTCCGAAGGAAAAATTGTCCATCTTGTCGTCTTCGGAAATGTTATGAAGCAGGGATGACTCTGGGAGCCCGGAAGCTGAAGAAACTTGGTAATCTGAAACTACAGGAGGAAGGAGAGGCTTCCAGCACCACCAGCCCCACTGAGGAGACAACCCAGAAGCTGACAGTGTCACACATTGAAGGCTATGAATGTCAGCCCATCTTTCTGAATGTCCTGGAAGCCATTGAGCCAGGTGTAGTGTGTGCTGGACACGACAACAACCAGCCCGACTCCTTTGCAGCCTTGCTCTCTAGCCTCAATGAACTGGGAGAGAGACAGCTTGTACACGTGGTCAAGTGGGCCAAGGCCTTGCCTGGCTTCCGCAACTTACACGTGGACGACCAGATGGCTGTCATTCAGTACTCCTGGATGGGGCTCATGGTGTTTGCCATGGGCTGGCGATCCTTCACCAATGTCAACTCCAGGATGCTCTACTTCGCCCCTGATCTGGTTTTCAATGAGTACCGCATGCACAAGTCCCGGATGTACAGCCAGTGTGTCCGAATGAGGCACCTCTCTCAAGAGTTTGGATGGCTCCAAATCACCCCCCAGGAATTCCTGTGCATGAAAGCACTGCTACTCTTCAGCATTATTCCAGTGGATGGGCTGAAAAATCAAAAATTCTTTGATGAACTTCGAATGAACTACATCAAGGAACTCGATCGTATCATTGCATGCAAAAGAAAAAATCCCACATCCTGCTCAAGACGCTTCTACCAGCTCACCAAGCTCCTGGACTCCGTGCAGCCTATTGCGAGAGAGCTGCATCAGTTCACTTTTGACCTGCTAATCAAGTCACACATGGTGAGCGTGGACTTTCCGGAAATGATGGCAGAGATCATCTCTGTGCAAGTGCCCAAGATCCTTTCTGGGAAAGTCAAGCCCATCTATTTCCACACCCAGTGA
"""

RAW["SFRP1"] = """
GCGCACTCCAGCCCTGCAGCCTCCGGAGTCAGTGCCGCGCGCCCGCCGCCCCGCGCCTTCCTGCTCGCCGCACCTCCGGGAGCCGGGGCGCACCCAGCCCGCAGCGCCGCCTCCCCGCCCGCGCCGCCTCCGACCGCAGGCCGAGGGCCGCCACTGGCCGGGGGGACCGGGCAGCAGCTTGCGGCCGCGGAGCCGGGCAACGCTGGGGACTGCGCCTTTTGTCCCCGGAGGTCCCTGGAAGTTTGCGGCAGGACGCGCGCGGGGAGGCGGCGGAGGCAGCCCCGACGTCGCGGAGAACAGGGCGCAGAGCCGGCATGGGCATCGGGCGCAGCGAGGGGGGCCGCCGCGGGGCAGCCCTGGGCGTGCTGCTGGCGCTGGGCGCGGCGCTTCTGGCCGTGGGCTCGGCCAGCGAGTACGACTACGTGAGCTTCCAGTCGGACATCGGCCCGTACCAGAGCGGGCGCTTCTACACCAAGCCACCTCAGTGCGTGGACATCCCCGCGGACCTGCGGCTGTGCCACAACGTGGGCTACAAGAAGATGGTGCTGCCCAACCTGCTGGAGCACGAGACCATGGCGGAGGTGAAGCAGCAGGCCAGCAGCTGGGTGCCCCTGCTCAACAAGAACTGCCACGCCGGCACCCAGGTCTTCCTCTGCTCGCTCTTCGCGCCCGTCTGCCTGGACCGGCCCATCTACCCGTGTCGCTGGCTCTGCGAGGCCGTGCGCGACTCGTGCGAGCCGGTCATGCAGTTCTTCGGCTTCTACTGGCCCGAGATGCTTAAGTGTGACAAGTTCCCCGAGGGGGACGTCTGCATCGCCATGACGCCGCCCAATGCCACCGAAGCCTCCAAGCCCCAAGGCACAACGGTGTGTCCTCCCTGTGACAACGAGTTGAAATCTGAGGCCATCATTGAACATCTCTGTGCCAGCGAGTTTGCACTGAGGATGAAAATAAAAGAAGTGAAAAAAGAAAATGGCGACAAGAAGATTGTCCCCAAGAAGAAGAAGCCCCTGAAGTTGGGGCCCATCAAGAAGAAGGACCTGAAGAAGCTTGTGCTGTACCTGAAGAATGGGGCTGACTGTCCCTGCCACCAGCTGGACAACCTCAGCCACCACTTCCTCATCATGGGCCGCAAGGTGAAGAGCCAGTACTTGCTGACGGCCATCCACAAGTGGGACAAGAAAAACAAGGAGTTCAAAAACTTCATGAAGAAAATGAAAAACCATGAGTGCCCCACCTTTCAGTCCGTGTTTAAGTGATTCTCCCGGGGGCAGGGTGGGGAGGGAGCCTCGGGTGGGGTGGGAGCGGGGGGGACAGTGCCCCGGGAACCCGGTGGGTCACACACACGCACTGCGCCTGTCAGTAGTGGACATTGTAATCCAGTCGGCTTGTTCTTGCAGCATTCCCGCTCCCTTCCCTCCATAGCCACGCTCCAAACCCCAGGGTAGCCATGGCCGGGTAAAGCAAGGGCCATTTAGATTAGGAAGGTTTTTAAGATCCGCAATGTGGAGCAGCAGCCACTGCACAGGAGGAGGTGACAAACCATTTCCAACAGCAACACAGCCACTAAAACACAAAAAGGGGGATTGGGCGGAAAGTGAGAGCCAGCAGCAAAAACTACATTTTGCAACTTGTTGGTGTGGATCTATTGGCTGATCTATGCCTTTCAACTAGAAAATTCTAATGATTGGCAAGTCACGTTGTTTTCAGGTCCAGAGTAGTTTCTTTCTGTCTGCTTTAAATGGAAACAGACTCATACCACACTTACAATTAAGGTCAAGCCCAGAAAGTGATAAGTGCAGGGAGGAAAAGTGCAAGTCCATTATGTAATAGTGACAGCAAAGGGACCAGGGGAGAGGCATTGCCTTCTCTGCCCACAGTCTTTCCGTGTGATTGTCTTTGAATCTGAATCAGCCAGTCTCAGATGCCCCAAAGTTTCGGTTCCTATGAGCCCGGGGCATGATCTGATCCCCAAGACATGTGGAGGGGCAGCCTGTGCCTGCCTTTGTGTCAGAAAAAGGAAACCACAGTGAGCCTGAGAGAGACGGCGATTTTCGGGCTGAGAAGGCAGTAGTTTTCAAAACACATAGTTAAAAAAGAAACAAATGAAAAAAATTTTAGAACAGTCCAGCAAATTGCTAGTCAGGGTGAATTGTGAAATTGGGTGAAGAGCTTAGGATTCTAATCTCATGTTTTTTCCTTTTCACATTTTTAAAAGAACAATGACAAACACCCACTTATTTTTCAAGGTTTTAAAACAGTCTACATTGAGCATTTGAAAGGTGTGCTAGAACAAGGTCTCCTGATCCGTCCGAGGCTGCTTCCCAGAGGAGCAGCTCTCCCCAGGCATTTGCCAAGGGAGGCGGATTTCCCTGGTAGTGTAGCTGTGTGGCTTTCCTTCCTGAAGAGTCCGTGGTTGCCCTAGAACCTAACACCCCCTAGCAAAACTCACAGAGCTTTCCGTTTTTTTCTTTCCTGTAAAGAAACATTTCCTTTGAACTTGATTGCCTATGGATCAAAGAAATTCAGAACAGCCTGCCTGTCCCCCCGCACTTTTTACATATATTTGTTTCATTTCTGCAGATGGAAAGTTGACATGGGTGGGGTGTCCCCATCCAGCGAGAGAGTTTCAAAAGCAAAACATCTCTGCAGTTTTTCCCAAGTACCCTGAGATACTTCCCAAAGCCCTTATGTTTAATCAGCGATGTATATAAGCCAGTTCACTTAGACAACTTTACCCTTCTTGTCCAATGTACAGGAAGTAGTTCTAAAAAAAATGCATATTAATTTCTTCCCCCAAAGCCGGATTCTTAATTCTCTGCAACACTTTGAGGACATTTATGATTGTCCCTCTGGGCCAATGCTTATACCCAGTGAGGATGCTGCAGTGAGGCTGTAAAGTGGCCCCCTGCGGCCCTAGCCTGACCCGGAGGAAAGGATGGTAGATTCTGTTAACTCTTGAAGACTCCAGTATGAAAATCAGCATGCCCGCCTAGTTACCTACCGGAGAGTTATCCTGATAAATTAACCTCTCACAGTTAGTGATCCTGTCCTTTTAACACCTTTTTTGTGGGGTTCTCTCTGACCTTTCATCGTAAAGTGCTGGGGACCTTAAGTGATTTGCCTGTAATTTTGGATGATTAAAAAATGTGTATATATATTAGCTAATTAGAAATATTCTACTTCTCTGTTGTCAAACTGAAATTCAGAGCAAGTTCCTGAGTGCGTGGATCTGGGTCTTAGTTCTGGTTGATTCACTCAAGAGTTCAGTGCTCATACGTATCTGCTCATTTTGACAAAGTGCCTCATGCAACCGGGCCCTCTCTCTGCGGCAGAGTCCTTAGTGGAGGGGTTTACCTGGAACATTAGTAGTTACCACAGAATACGGAAGAGCAGGTGACTGTGCTGTGCAGCTCTCTAAATGGGAATTCTCAGGTAGGAAGCAACAGCTTCAGAAAGAGCTCAAAATAAATTGGAAATGTGAATCGCAGCTGTGGGTTTTACCACCGTCTGTCTCAGAGTCCCAGGACCTTGAGTGTCATTAGTTACTTTATTGAAGGTTTTAGACCCATAGCAGCTTTGTCTCTGTCACATCAGCAATTTCAGAACCAAAAGGGAGGCTCTCTGTAGGCACAGAGCTGCACTATCACGAGCCTTTGTTTTTCTCCACAAAGTATCTAACAAAACCAATGTGCAGACTGATTGGCCTGGTCATTGGTCTCCGAGAGAGGAGGTTTGCCTGTGATTTCCTAATTATCGCTAGGGCCAAGGTGGGATTTGTAAAGCTTTACAATAATCATTCTGGATAGAGTCCTGGGAGGTCCTTGGCAGAACTCAGTTAAATCTTTGAAGAATATTTGTAGTTATCTTAGAAGATAGCATGGGAGGTGAGGATTCCAAAAACATTTTATTTTTAAAATATCCTGTGTAACACTTGGCTCTTGGTACCTGTGGGTTAGCATCAAGTTCTCCCCAGGGTAGAATTCAATCAGAGCTCCAGTTTGCATTTGGATGTGTAAATTACAGTAATCCCATTTCCCAAACCTAAAATCTGTTTTTCTCATCAGACTCTGAGTAACTGGTTGCTGTGTCATAACTTCATAGATGCAGGAGGCTCAGGTGATCTGTTTGAGGAGAGCACCCTAGGCAGCCTGCAGGGAATAACATACTGGCCGTTCTGACCTGTTGCCAGCAGATACACAGGACATGGATGAAATTCCCGTTTCCTCTAGTTTCTTCCTGTAGTACTCCTCTTTTAGATCCTAAGTCTCTTACAAAAGCTTTGAATACTGTGAAAATGTTTTACATTCCATTTCATTTGTGTTGTTTTTTTAACTGCATTTTACCAGATGTTTTGATGTTATCGCTTATGTTAATAGTAATTCCCGTACGTGTTCATTTTATTTTCATGCTTTTTCAGCCATGTATCAATATTCACTTGACTAAAATCACTCAATTAATCAA
"""

SEQS = {nm: dna2rna(re.sub(r"\s+", "", raw)) for nm, raw in RAW.items()}


def design_for(name, top=5):
    mrna = SEQS[name]
    pool_others = [(n, s) for n, s in SEQS.items() if n != name]
    rows = []
    seen = set()
    for pos, sense in slide_candidates(mrna, 19):
        if "N" in sense or sense in seen:
            continue
        seen.add(sense)
        g = gc(sense)
        if g < 25 or g > 60:           # hard GC gate
            continue
        if has_run(sense, 5):          # reject runs >=5
            continue
        rey = reynolds_score(sense)
        ut_ok, ut_reasons = uitei_pass(sense)
        asym = asymmetry(sense)        # more negative = better
        synth = synthesizability(sense)
        seed = seed_of(sense)
        off_cross = count_seed_offtarget(seed, pool_others)
        off_self = count_seed_offtarget(seed, [(name, mrna)])  # includes on-site
        on_score = (rey / 8.0) + (0.5 if ut_ok else 0.0)
        asym_bonus = max(0.0, min(0.5, (-asym) / 6.0))
        on_score += asym_bonus
        off_factor = 1.0 / (1.0 + off_cross)
        rank_score = on_score * off_factor * synth
        rows.append({
            "pos": pos, "sense": sense, "guide": revcomp_rna(sense),
            "gc": round(g, 1), "reynolds": rey,
            "uitei": "PASS" if ut_ok else "fail:" + ",".join(ut_reasons),
            "asym_ddG": round(asym, 2), "synth": round(synth, 2),
            "seed": seed, "off_cross": off_cross, "off_self": off_self,
            "on_score": round(on_score, 3), "rank_score": round(rank_score, 4),
        })
    rows.sort(key=lambda r: (r["uitei"] != "PASS", -r["rank_score"]))
    return rows[:top]


if __name__ == "__main__":
    for name in ["DKK1", "SRD5A2", "AR", "SFRP1"]:
        print("=" * 78)
        print(f"# {name}  (len={len(SEQS[name])} nt)")
        print("=" * 78)
        for i, r in enumerate(design_for(name, 5), 1):
            print(f"[{name}-{i}] pos {r['pos']:>4}  GC {r['gc']:>4}%  "
                  f"Rey {r['reynolds']}/8  UiTei {r['uitei']:<14}  "
                  f"asym {r['asym_ddG']:>6}  synth {r['synth']}  "
                  f"off_cross {r['off_cross']}  off_self {r['off_self']}  "
                  f"score {r['rank_score']}")
            print(f"        sense 5'-{r['sense']}-3'")
            print(f"        guide 5'-{r['guide']}-3'  seed[2-8]={r['seed']}")
